web/router.ex
defmodule PandaPhoenix.Router do
  @moduledoc false

  use PandaPhoenix.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :auth do
   plug PandaPhoenix.Plug.Authenticate
  end

  pipeline :rate do
   plug PandaPhoenix.Plug.RateLimit
  end

  scope "/", PandaPhoenix do
    pipe_through :browser # Use the default browser stack

    get "/", HomeController, :index
    get "/active", HomeController, :active_user
    get "/reset", HomeController, :reset
    post "/reset/:token/password", HomeController, :reset_password
    get "/:language/terms", HomeController, :terms
  end

  scope "/api", PandaPhoenix do
    pipe_through :api
    pipe_through :rate

    scope "/v1" do

      post "/auth", UserAuthenticationController, :login
      post "/auth/renew", UserAuthenticationController, :renew_token
      resources "/register", UserController, only: [:create]
      post "/reset_password", UserController, :reset_password
    end
  end

  scope "/api", PandaPhoenix do
    pipe_through :api
    pipe_through :auth

    scope "/v1" do

      post "/logout", UserAuthenticationController, :logout
      get "/auth/backup", BackupController, :backup
      get "/pending/backup", BackupController, :backup_pending_data

      post "/confirmation/messages", MessageSenderController, :private_messages_confirmation
      post "/broadcast/message", MessageSenderController, :public_message

      # Filter (Resfull)
      resources "/filters", UserFilterController, only: [:create, :update, :delete]
      # get "/user_filters", UserFilterController, :user_filters

      # Public Room
      post "/find_room", PublicRoomLocalizationController, :find_room

      resources "/users", UserController, only: [:show, :update]

      # Friendship
      post "/update_friendship", UserFriendshipController, :update_friendship
      # post "/list_accepted_friendships", UserFriendshipController, :list_accepted_friendships
      # post "/list_pending_friendships", UserFriendshipController, :list_pending_friendships
      # post "/list_blocked_friendships", UserFriendshipController, :list_blocked_friendships
      post "/find_friendships", UserFriendshipController, :find

      resources "/report", UserReportController, only: [:create]
      post "/push_token", UserAuthenticationController, :push_token

      post "/upload/image", DataController, :upload_image

      # post "/user_reported_remove", UserReportedController, :user_reported_remove
      # post "/user_reported_get", UserReportedController, :user_reported_get

      # resources "/user_socials", UserSocialController, except: [:new, :edit]
      # resources "/datas", DataController, except: [:new, :edit]
      # resources "/public_rooms", PublicRoomController, except: [:new, :edit]
      # resources "/private_rooms", PrivateRoomController, except: [:new, :edit]
      #
      # resources "/user_filters", UserFilterController, except: [:new, :edit]
      # # resources "/public_room_localization", PublicRoomLocalizationController, except: [:new, :edit]
      #
      # resources "/private_messages", PrivateMessageController, except: [:new, :edit]
      # resources "/private_room_users", PrivateRoomUserController, except: [:new, :edit]
      # resources "/public_messages", PublicMessageController, except: [:new, :edit]
      # resources "/user_friendships", UserFriendshipController, except: [:new, :edit]
      # resources "/user_passwords", UserPasswordController, except: [:new, :edit]
    end
  end

end

web/views/home_view.ex
defmodule PandaPhoenix.HomeView do
  use PandaPhoenix.Web, :view
end

web/templates/home/index.html.eex
<div class="jumbotron1">
  <div class ="container">
    <div class="row">
      <div class="col-xs-offset-6 col-xs-6
                  col-sm-offset-6 col-sm-5
                  col-md-offset-6 col-md-5">
          <!-- <div class ="title">.panda</div> -->
          <div class="title">
            <img class="img-responsive" src="/images/logo_text.png">
          </div>
          <div class="message2">Get the App</div>
      </div>
    </div>
  </div>
</div>
<div class="jumbotron2" >
  <div class="container">
    <div class="clearfix visible-sm-block visible-md-block visible-lg-block">
      <div class="row">
            <div class="clearfix visible-lg-block">
            <br>
            </div>
            <br>
            <div class="col-lg-7 col-md-6 col-sm-6"> </div>
            <div class="col-lg-2 col-md-3 col-sm-3">
              <a href="https://itunes.apple.com/us/app/panda/id1148413735?ls=1&mt=8">
                <img class="img-responsive" src="/images/button_apple.png" padding="5px">
              </a>
            </div>
            <div class="col-lg-2 col-md-3 col-sm-3">
                <img class="img-responsive" src ="/images/button_google_play.png" padding="5px">
            </div>
      </div>
      <div class="row">
        <div class="col-lg-9 col-md-9 col-sm-9"> </div>
        <div class="col-lg-2 col-md-2 col-sm-3">
            <div class="control-label">(soon)</div>
        </div>
      </div>
    </div>
    <div class="clearfix visible-xs-block">
      <br>
      <div class="row">
        <div class="col-xs-7"> </div>
        <div class="col-xs-5">
          <a href="https://itunes.apple.com/us/app/panda/id1148413735?ls=1&mt=8">
            <img class="img-responsive" src="/images/button_apple.png">
          </a>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-xs-7"> </div>
        <div class="col-xs-5">
            <img class="img-responsive" src ="/images/button_google_play.png">
        </div>
      </div>
      <div class="row">
        <div class="col-xs-offset-7">
            <div class="control-label">(soon)</div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="panda">
    <img class="img-responsive" src="images/logo_panda.png">
</div>

web/templates/home/reponse.html.eex
<div class="jumbotron1">
  <div class ="container">
    <div class="row">
      <div class="col-xs-offset-5 col-xs-6
                  col-sm-offset-6 col-sm-5
                  col-md-offset-6 col-md-5">
          <div class ="title3"><%= @title %></div>
          <div class="message3"><%= @message %></div>
      </div>
    </div>
  </div>
</div>
<div class="jumbotron2" >
  <div class="container">
    <div class="row">
        <div class="clearfix visible-lg-block">
          <br>
        </div>
          <br>
        <div class="col-xs-offset-5 col-xs-6
                    col-sm-offset-6 col-sm-5
                    col-md-offset-6 col-md-5">
          <div class="info">
            <%= link "Go Home", to: home_path(@conn, :index) %>
          </div>
        </div>
      </div>
  </div>
</div>
<div class="panda">
  <%= if @success do %>
    <img class="img-responsive" src="/images/logo_panda_success.png">
  <% else %>
    <img class="img-responsive" src="/images/logo_panda_error.png">
  <% end %>
</div>

web/templates/home/reset.html.eex
<%= form_for @changeset, @action, fn f -> %>
<%= if @changeset.valid? == false do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
<% end %>
<div class="jumbotron1">
  <div class ="container">
    <div class="row">
      <div class="col-xs-offset-2 col-xs-8
                  col-sm-offset-3 col-sm-5
                  col-md-offset-3 col-md-5">
          <div class ="title3">.panda</div>
          <div class="message3">Reset Password</div>
      </div>
    </div>
  </div>
</div>
<div class="jumbotron2" >
  <div class="container">
    <div class="row">
      <div class="col-xs-offset-2 col-xs-8
                  col-sm-offset-3 col-sm-5
                  col-md-offset-3 col-md-5
                  col-lg-offset-3 col-lg-5">
        <div class="form-group">
          <%= label f, :new_password, class: "control-label" %>
          <%= password_input f, :new_password, [class: "form-control"] %>
          <%= error_tag f, :new_password %>
        </div>
      </div>
      <div class="col-xs-offset-2 col-xs-8
                  col-sm-offset-3 col-sm-5
                  col-md-offset-3 col-md-5
                  col-lg-offset-3 col-lg-5">
        <div class="form-group">
          <%= label f, :confirm_password, class: "control-label" %>
          <%= password_input f, :confirm_password, [class: "form-control"] %>
          <%= error_tag f, :confirm_password %>
        </div>
      <div class="col-xs-offset-1 col-xs-10
                  col-sm-offset-3 col-sm-6
                  col-md-offset-3 col-md-6
                  col-lg-offset-3 col-lg-6">
          <div class="form-group">
            <%= submit "Reset", class: "btn btn-default" %>
          </div>
      </div>
    </div>
  </div>
</div>
<% end %>

web/templates/home/term_and_condition.html.eex
<div class="jumbotron1">
  <div class ="container">
    <div><%= raw(@content) %></div>
  </div>
</div>